{
 "title": "Burrow - Evaluated Lag",
 "tags": [
  "kafka",
  "burrow"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Groups OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_health_count\" AND status:\"OK\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Groups WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_health_count\" AND status:\"WARN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Groups ERR+",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_health_count\" AND status:\"ERRPLUS\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Lights: Burrow Group Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "{{term group}}",
     "bucketAggs": [
      {
       "field": "group",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_status_code\" AND group:demo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Burrow Status Code Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "{{term group}}",
     "bucketAggs": [
      {
       "field": "group",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_status_code\" AND group:demo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Burrow Bad Partitions by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "alias": "{{term group}}",
     "bucketAggs": [
      {
       "field": "group",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_bad_partitions\" AND group:demo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Burrow Max Lag by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "{{term group}}",
     "bucketAggs": [
      {
       "field": "group",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_max_lag\" AND group:demo-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Burrow Complete Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "alias": "{{term group}}",
     "bucketAggs": [
      {
       "field": "group",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "source:burrow AND metric:\"burrow_group_complete\" AND group:demo-*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}